^INCLUDE:jenkins/configs/includes/properties.yaml<abortIfNotLatest=abortIfNotLatest: "soft">; # aborts the PR's current build if there is a newer one running

releasename: ^PARAM:RELEASE_NAME;
variant: ^PARAM:VARIANT_NAME;
export: ^PARAM:RNG_EXPORT;
convert: ^PARAM:RNG_CONVERT;
compile: ^PARAM:RNG_COMPILE;
create: ^PARAM:RNG_CREATE;
publish: ^PARAM:RNG_PUBLISH;
sign: ^PARAM:RNG_SIGN;

<%
int order = 0
%>

pipelines:
- nodes: 
  - label: L4_Prem_C1
    executionOrder: 0
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/rng_unstash.yaml<execOrder=${++order}, releasename=^YAML:releasename; , variant=^YAML:variant;>;
    - ^INCLUDE:jenkins/configs/includes/07_rng_developer_build.yaml<execOrder=${++order}, export=^YAML:export; , convert=^YAML:convert; , compile=^YAML:compile; , create=^YAML:create; , publish=^YAML:publish;>;
    - ^INCLUDE:jenkins/configs/includes/rng_stash.yaml<execOrder=${++order}, releasename=^YAML:releasename; , variant=^YAML:variant; >;
