    - name: rng create
      executionOrder: ^TPL:execOrder;
      steps:
      - cmd: 04_rng_create.bat
        fromPath: ./ad_radar_apl/tools/rng
        name: rng_create
      archive:
      - backend: share
        sharePath: \\abtvdfs1.de.bosch.com\ismdfs\ida\abt\SW_Build\Radar\SystemC\Athena_Radar\CI\^ENV:LUCX_JOB_NAME_WINDOWS;\^ENV:BUILD_NUMBER;\RNG_create
        fromPath: ./ad_radar_apl/tools/rng/
        includes: "rn_TestProject/**"
        afterFail: false
        zip: false
      