    - name: buildInfo
      executionOrder: ^TPL:execOrder;
      steps:
      - cmd: buildInfoCfg.bat ^TPL:variant;
        fromPath: ./jenkins/scripts/rng
        name: build_Info
      archive:
      - backend: share
        sharePath: \\abtvdfs1.de.bosch.com\ismdfs\ida\abt\SW_Build\Radar\SystemC\Athena_Radar\CI\^ENV:LUCX_JOB_NAME_WINDOWS;\^ENV:BUILD_NUMBER;\^TPL:variant;_rng\
        fromPath: ./ad_radar_apl/tools/rng/
        includes: "rn_TestProject/**"
        afterFail: false
        zip: true
        zipName: rng_^TPL:variant;