    - name: FR5CU_specifications_gen
      executionOrder: ^TPL:execOrder;
      steps:
      - cmd: python FR5CU_spec_generate_pdf.py
        fromPath: ad_radar_apl/doc
        name: FR5CU_specifications_generation
      archive:
      - backend: share
        fromPath: ./ad_radar_apl/doc/
        includes: "*.pdf"
        afterFail: false
        zip: true
        zipName: FR5CU_Specification_Document.zip
      publish:
        - reportName: FR5CU_Specification_Documentation
          reportDir: ./ad_radar_apl/doc
          reportFiles: FR5CU_Specification_Document.pdf
          reportTitles: FR5CU Specification Document
