# scom options! Can be moved to a separate project specific config file.
	set(RB_PROJECT_SCOM_FLUX_FILE "ad_radar_apl/arch/system.flux")
	set(FLUX_FILE "${RB_PROJECT_SCOM_FLUX_FILE}")
	set(RB_FP_SCOMGENERATOR_EXECUTABLE "C:/TCC/Tools/ScomGenerator/8.1.0_WIN64/ScomGenerator.exe")
	set(SYSTEM_INSTANCE "AD_Radar_PF")
	set(OS "RTA_OS")
	set(RB_PROJECT_SCOM_SOURCEFILE "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2")
	set(SCOM_PATH "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2")
	set(LOG "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2/scom_gen_log.txt")
	set(CONFIG "aurix_plus")
	set(RB_PROJECT_SCOM_XML_FILE "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2/scom.xml")
	set(RB_PROJECT_SCOM_OUT "ad_radar_apl_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2")
	set(DynAddrSig_static "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2/DynAddrSig_static.h")
	set(MempoolOptSize "ad_radar_apl/ToBeCleanUp/scom_gen/FR5CU_DENN1_CEN_N_XX_2_uC2/mempoolsize.csv")
	set(Var "target/Radar_FR5CU_DENN1_CEN_N_XX_2_uC2")