^INCLUDE:jenkins/configs/includes/properties.yaml<abortIfNotLatest=abortIfNotLatest: "soft">; # aborts the PR's current build if there is a newer one running

uc1: FR5CU_DNNN1_NNN_N_XX_2_uC1
uc2: FR5CU_DENN1_CEN_N_XX_2_uC2

cmake_cfg_path: ad_radar_apl/tools/cmake/cfg

a2l_build_env: jenkins
variant_FR5CU: FR5CU

hw: C0

IntTest_ROOT_DIR: C:\ws\aras@1\repo\

user_id: cis9lr

<%
int order = 0
%>
<%
int nodeOrder = 0
%>

pipelines:
- nodes: 
  - label: ATR
    executionOrder: ${nodeOrder=0}
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/FetchTags.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/Doxygen.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/FR5CUSpecGen.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader.yaml<execOrder=${++order}, user_id=^YAML:user_id;>;
    - ^INCLUDE:jenkins/configs/includes/GeneratePDM.yaml<execOrder=${++order}, build_variant=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/BuildSW.yaml<execOrder=${++order}, build_variant=^YAML:uc1;, cfg_path=^YAML:cmake_cfg_path;, variant=uc1, threshold=175>;
    - ^INCLUDE:jenkins/configs/includes/BuildSW.yaml<execOrder=${++order}, build_variant=^YAML:uc2;, cfg_path=^YAML:cmake_cfg_path;, variant=uc2, threshold=193>;
    - ^INCLUDE:jenkins/configs/includes/PlantContainer_Nightly.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;

  - label: Canape_license
    executionOrder: ${++nodeOrder}
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/Unstash.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/FR5CUSpecGen.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/A2LUpdate.yaml<execOrder=${++order}, a2l_build_env=^YAML:a2l_build_env;, variant=^YAML:variant_FR5CU;>;
    - ^INCLUDE:jenkins/configs/includes/MTUpdate.yaml<execOrder=${++order}, variant=^YAML:variant_FR5CU;, ROOT_DIR=^YAML:IntTest_ROOT_DIR;, VAR1=^YAML:uc1;, VAR2=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/StoreArtifacts.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/CT_Trigger.yaml<execOrder=${++order}, variant=^YAML:variant_FR5CU;, hw=^YAML:hw;, release=false>;