# -*- coding: utf-8 -*-


#constants for configuration
CONST_DEFAULT_ADDRESS                                   = "0"
CONST_USERDEFINED_SET1                                  = "1"
CONST_USERDEFINED_SET2                                  = "2"
CONST_USERDEFINED_SET3                                  = "3"
CONST_USERDEFINED_SET4                                  = "4"

#constants for TX PDU
CONST_LOCATION_ATTRIBUTE_TX                             = 0
CONST_LOCATION_DATA0_TX                                 = 1
CONST_SENSOR_STATE_TX									= 2
CONST_SENSOR_FEEDBACK_TX								= 3
CONST_SENSOR_BROADCAST_TX								= 4

#RADAR IP Range 1 constants
CONST_USERDEFINED_RADAR_IP_RANGE_1                      = "0a000001"
CONST_USERDEFINED_RADAR_IP_RANGE_2                      = "ac100001"
CONST_USERDEFINED_RADAR_IP_RANGE_3                      = "c0a80001"
CONST_USERDEFINED_RADAR_IP_RANGE_4                      = "c0a80002"


#Remote IP Range 2 constants
CONST_USERDEFINED_REMOTE_IP_RANGE_1                     = "0afffffe"
CONST_USERDEFINED_REMOTE_IP_RANGE_2                     = "ac1ffffe"
CONST_USERDEFINED_REMOTE_IP_RANGE_3                     = "c0a8fffe"
CONST_USERDEFINED_REMOTE_IP_RANGE_4                     = "c0a8ff00"


#LOCAL IP constants
CONST_DEFAULT_RADAR_IP_ADDRESS                          = "c0a82833"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET1                 = "c0a80001"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET2                 = "c0a8fffe"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET3                 = "0a000001"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET4                 = "c0a80001"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET5                 = "c0a80002"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET7                 = "c0a80000"
CONST_DEFAULT_RADAR_IP_ADDRESS_HEX                      = "0xc0a82833"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET1_HEX             = "0xc0a80001"
CONST_USERDEFINED_RADAR_IP_CLASS_C_SET2_HEX             = "0xc0a8fffe"
CONST_USERDEFINED_INVALID_CLASS_C                       = "c0a8ffff"

#MAC constants
CONST_DEFAULT_RADAR_MAC_ADDRESS                         = "8834fe000001" 
CONST_USERDEFINED_MAC_SET1                              = "8834fe851125" 
CONST_USERDEFINED_MAC_SET2                              = "8834fe456398" 
CONST_USERDEFINED_MAC_SET1_HEX                          = '0x8834fe851125'
CONST_USERDEFINED_MAC_SET2_HEX                          = '0x8834fe456398'
CONST_DEFAULT_DEST_MAC_BROADCAST_ADDRESS                = '0xffffffffffff'

#constants for NVM flag
CONST_DEFAULT_NVM_FLAG                                  = "00"
CONST_USER_DEFINED_NVM_FLAG                             = "01"
CONST_PREVIOUS_IP_NVM_FLAG                              = "02"

#constants for variant handling
CONST_LOCAL_IP                                          = "1"
CONST_REMOTE_IP                                         = "2"
CONST_REMOTE_PORT                                       = "3"
CONST_REMOTE_IP_MULTICAST                               = "4"
CONST_RADAR_MAC                                         = "5"
CONST_USER_IP                                           = "6"


#constants for DMP
CONST_MEAS_PGM_DMP01                                    = 1
CONST_MEAS_PGM_DMP02                                    = 2
CONST_MEAS_PGM_DMP04                                    = 4

#constants for sensor mode request
CONST_SENSOR_MODE_START_MODULTATION                     = 1
CONST_SENSOR_MODE_STOP_MODULTATION                      = 2
CONST_SENSOR_MODE_SUSPEND_MODULTATION                   = 3
CONST_COM_SENSOR_MODE_REQUEST_START_MODULATION          = "01"
CONST_COM_SENSOR_MODE_REQUEST_STOP_MODULATION           = "02"
CONST_COM_SENSOR_MODE_REQUEST_SUSPEND_MODULATION        = "03"

#constants for MCS
CONST_SENSORTIME_44_MILLI_SECONDS_PDU                   = 44000000
CONST_SENSORTIME_22_MILLI_SECONDS_PDU                   = 22000000
CONST_SENSORTIME_33_MILLI_SECONDS_PDU                   = 33000000
CONST_SENSORTIME_SLOT_SYNCHTYPE                         = 1

#constants for ego vehicle speed
CONST_EGO_VEHICLE_SPEED_MIN                             = -100.0
CONST_EGO_VEHICLE_YAWRATE_MIN                           = -114.59
CONST_EGO_VEHICLE_SPEED_STDDEV_MIN                      = -128.0
CONST_EGO_VEHICLE_ACCEL_MIN                             = -16.0

CONST_EGO_VEHICLE_SPEED_MAX                             = 100.0
CONST_EGO_VEHICLE_YAWRATE_MAX                           = 114.59
CONST_EGO_VEHICLE_SPEED_STDDEV_MAX                      = 127.99
CONST_EGO_VEHICLE_ACCEL_MAX                             = 15.99

CONST_EGO_VEHICLE_SPEED_MID                             = 50.0
CONST_EGO_VEHICLE_YAWRATE_MID                           = 100.0
CONST_EGO_VEHICLE_SPEED_STDDEV_MID                      = 70.0
CONST_EGO_VEHICLE_ACCEL_MID                             = 10.0



#REMOTE IP constants
CONST_DEFAULT_REMOTE_IP_ADDRESS                         = "c0a82802"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET1                = "c0a80005"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET2                = "c0a8fffc"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET3                = "0afffffe"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET4                = "ac1ffffe"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET5                = "c0a8ff00"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET6                = "c0a8fffe"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET7                = "c0a8ffff"
CONST_DEFAULT_REMOTE_IP_ADDRESS_HEX                     = "0xc0a82802"
CONST_DEFAULT_REMOTE_IP_ADDRESS_BROADCAST_HEX           = "0xffffffff"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET1_HEX            = "0xc0a80005"
CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET2_HEX            = "0xc0a8fffc"

CONST_USERDEFINED_REMOTE_MULTICAST_IP_HEX               = "0xe0000001"
CONST_MULTICAST_REMOTE_IP                               = "e0000001"

#REMOTE PORT constants
CONST_DEFAULT_REMOTE_PORT_NUMBER_HEX                    = "0x76c0"
CONST_DEFAULT_REMOTE_PORT_NUMBER                        = "76c0"
CONST_USER_DEFINED_REMOTE_PORT_SET1                     = "8756"
CONST_USER_DEFINED_REMOTE_PORT_SET2                     = "9645"
CONST_USER_DEFINED_REMOTE_PORT_SET1_HEX                 = "0x8756"
CONST_USER_DEFINED_REMOTE_PORT_SET2_HEX                 = "0x9645"
CONST_USER_DEFINED_REMOTE_PORT_INVALID                  = "dfff"
CONST_USER_DEFINED_REMOTE_PORT_SET3                     = "400"
CONST_USER_DEFINED_REMOTE_PORT_SET4                     = "bfff"
CONST_USER_DEFINED_REMOTE_PORT_SET5                     = "6500"
CONST_USER_DEFINED_REMOTE_PORT_SET6                     = "64fe"
CONST_USER_DEFINED_REMOTE_PORT_SET7                     = "c000"


#SOURCE PORT constants
CONST_DEFAULT_SOURCE_PORT_NUMBER                        = "0x76c6"
CONST_DEFAULT_SOURCE_PORT_NUMBER_BROADCAST              = "0x7600"

#Diag source IP constants
CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS                    = "a9fe1295"
CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET1          = "a9fe0001"
CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET2          = "a9fefffe"
CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET3          = "a9feffff"

#DOIP constants
CONST_DEFAULT_RADAR_DOIP_ADDRESS                        = "1295"
CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET1              = "0001"
CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET2              = "ffff"
CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET3              = "1345"

#IP constants for source and remote IP
CONST_RADAR_IP_ADDRESS_SET1_HEX                         = "0xa000001"
CONST_RADAR_IP_ADDRESS_SET2_HEX                         = "0xac100001"
CONST_RADAR_IP_ADDRESS_SET3_HEX                         = "0xc0a80001"
CONST_RADAR_IP_ADDRESS_SET4_HEX                         = "0xc0a80002"
CONST_REMOTE_IP_ADDRESS_SET1_HEX                        = "0xafffffe"
CONST_REMOTE_IP_ADDRESS_SET2_HEX                        = "0xac1ffffe"
CONST_REMOTE_IP_ADDRESS_SET3_HEX                        = "0xc0a8fffe"
CONST_REMOTE_IP_ADDRESS_SET4_HEX                        = "0xc0a8ff00"

CONST_DUMMY_BYTE                                        = "00"
CONST_DID_READ_REQ_IP_ADDRESS                           = "220600"
CONST_DID_READ_RESP_IP_ADDRESS                          = "620600"
CONST_DID_READ_REQ_DOIP_ADDRESS                         = "220602"
CONST_DID_READ_RESP_DOIP_ADDRESS                        = "620602"
CONST_DID_READ_REQ_MAC_ADDRESS                          = "220601"
CONST_DID_READ_RESP_MAC_ADDRESS                         = "620601"

CONST_DID_WRITE_REQ_IP_ADDRESS                          = "2e0600"
CONST_DID_WRITE_RESP_IP_ADDRESS                         = "6e0600"
CONST_DID_WRITE_REQ_DOIP_ADDRESS                        = "2e0602"
CONST_DID_WRITE_RESP_DOIP_ADDRESS                       = "6e0602"
CONST_DID_WRITE_REQ_MAC_ADDRESS                         = "2e0601"
CONST_DID_WRITE_RESP_MAC_ADDRESS                        = "6e0601"

CONST_DID_READ_REQ_REMOTE_PORT                          = "22060d"
CONST_DID_READ_RESP_REMOTE_PORT                         = "62060d"
CONST_DID_WRITE_REQ_REMOTE_PORT                         = "2e060d"
CONST_DID_WRITE_RESP_REMOTE_PORT                        = "6e060d"


CONST_READ_RESP_DEFAULT_IP_ADDRESS                      = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_RADAR_IP_CLASS_C_SET1       = CONST_DID_READ_RESP_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_CLASS_C_SET1 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_RADAR_IP_CLASS_C_SET2       = CONST_DID_READ_RESP_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_CLASS_C_SET2 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 

CONST_WRITE_REQ_DEFAULT_RADAR_IP_ADDRESS                = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + 11*CONST_DUMMY_BYTE
CONST_WRITE_REQ_USERDEFINED_RADAR_IP_CLASS_C_SET1       = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_CLASS_C_SET1 + CONST_USER_DEFINED_NVM_FLAG + 11*CONST_DUMMY_BYTE
CONST_WRITE_REQ_USERDEFINED_RADAR_IP_CLASS_C_SET2       = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_CLASS_C_SET2 + CONST_USER_DEFINED_NVM_FLAG + 11*CONST_DUMMY_BYTE
CONST_WRITE_REQ_INVALID_RADAR_IP_CLASS_C                = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_INVALID_CLASS_C + CONST_USER_DEFINED_NVM_FLAG + 11*CONST_DUMMY_BYTE    

CONST_WRITE_REQ_USERDEFINED_REMOTE_IP_CLASS_C_SET1      = CONST_DID_WRITE_REQ_IP_ADDRESS + 5*CONST_DUMMY_BYTE + CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET1 + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_WRITE_REQ_USERDEFINED_REMOTE_IP_CLASS_C_SET2      = CONST_DID_WRITE_REQ_IP_ADDRESS + 5*CONST_DUMMY_BYTE + CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET2 + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_REMOTE_IP_CLASS_C_SET1      = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET1 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_REMOTE_IP_CLASS_C_SET2      = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_CLASS_C_SET2 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_WRITE_REQ_INVALID_REMOTE_IP_CLASS_C               = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_INVALID_CLASS_C + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE   

CONST_READ_RESP_DEFAULT_REMOTE_IP_ADDRESS               = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_WRITE_REQ_DEFAULT_REMOTE_IP_ADDRESS               = CONST_DID_WRITE_REQ_IP_ADDRESS + 5*CONST_DUMMY_BYTE + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + 6*CONST_DUMMY_BYTE

CONST_WRITE_REQ_MULTICAST_REMOTE_IP                     = CONST_DID_WRITE_REQ_IP_ADDRESS + 4*CONST_DUMMY_BYTE + CONST_PREVIOUS_IP_NVM_FLAG + CONST_MULTICAST_REMOTE_IP + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_MULTICAST_REMOTE_IP                     = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_MULTICAST_REMOTE_IP + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 


CONST_DID_READ_RESP_DEFAULT_REMOTE_PORT                 = CONST_DID_READ_RESP_REMOTE_PORT + CONST_DEFAULT_REMOTE_PORT_NUMBER + 5*CONST_DUMMY_BYTE + CONST_DEFAULT_NVM_FLAG
CONST_WRITE_REQ_USERDEFINED_REMOTE_PORT_SET1            = CONST_DID_WRITE_REQ_REMOTE_PORT + CONST_USER_DEFINED_REMOTE_PORT_SET1 + 5*CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_READ_RESP_USERDEFINED_REMOTE_PORT_SET1            = CONST_DID_READ_RESP_REMOTE_PORT + CONST_USER_DEFINED_REMOTE_PORT_SET1 + 5*CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG      

CONST_WRITE_REQ_USERDEFINED_REMOTE_PORT_SET2            = CONST_DID_WRITE_REQ_REMOTE_PORT + CONST_USER_DEFINED_REMOTE_PORT_SET2 + 5*CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_READ_RESP_USERDEFINED_REMOTE_PORT_SET2            = CONST_DID_READ_RESP_REMOTE_PORT + CONST_USER_DEFINED_REMOTE_PORT_SET2 + 5*CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG      

CONST_WRITE_REQ_INVALID_REMOTE_PORT                     = CONST_DID_WRITE_REQ_REMOTE_PORT + CONST_USER_DEFINED_REMOTE_PORT_INVALID + 5*CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_WRITE_REQ_DEFAULT_REMOTE_PORT_NUMBER              = CONST_DID_WRITE_REQ_REMOTE_PORT + CONST_DEFAULT_REMOTE_PORT_NUMBER + 5*CONST_DUMMY_BYTE + CONST_DEFAULT_NVM_FLAG 


CONST_READ_RESP_DEFAULT_VARIANT_HANDLING                = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 


CONST_WRITE_REQ_DEFAULT_MAC_ADDRESS                     = CONST_DID_WRITE_REQ_MAC_ADDRESS + CONST_DEFAULT_RADAR_MAC_ADDRESS + CONST_DUMMY_BYTE + CONST_DEFAULT_NVM_FLAG
CONST_READ_RESP_DEFAULT_MAC_ADDRESS                     = CONST_DID_READ_RESP_MAC_ADDRESS + CONST_DEFAULT_RADAR_MAC_ADDRESS + CONST_DUMMY_BYTE + CONST_DEFAULT_NVM_FLAG
CONST_WRITE_REQ_USERDEFINED_RADAR_MAC_SET1              = CONST_DID_WRITE_REQ_MAC_ADDRESS + CONST_USERDEFINED_MAC_SET1 + CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_READ_RESP_USERDEFINED_RADAR_MAC_SET1              = CONST_DID_READ_RESP_MAC_ADDRESS + CONST_USERDEFINED_MAC_SET1 + CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_WRITE_REQ_USERDEFINED_RADAR_MAC_SET2              = CONST_DID_WRITE_REQ_MAC_ADDRESS + CONST_USERDEFINED_MAC_SET2 + CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG
CONST_READ_RESP_USERDEFINED_RADAR_MAC_SET2              = CONST_DID_READ_RESP_MAC_ADDRESS + CONST_USERDEFINED_MAC_SET2 + CONST_DUMMY_BYTE + CONST_USER_DEFINED_NVM_FLAG



CONST_READ_RESP_DEFAULT_DIAG_SOURCE_IP_ADDRESS          = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_WRITE_REQ_USERDEFINED_RADAR_DIAG_SOURCE_IP_SET1   = CONST_DID_WRITE_REQ_IP_ADDRESS + 10*CONST_DUMMY_BYTE + CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET1 + CONST_USER_DEFINED_NVM_FLAG + CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_RADAR_DIAG_SOURCE_IP_SET1   = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET1 + CONST_USER_DEFINED_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_WRITE_REQ_USERDEFINED_RADAR_DIAG_SOURCE_IP_SET2   = CONST_DID_WRITE_REQ_IP_ADDRESS + 10*CONST_DUMMY_BYTE + CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET2 + CONST_USER_DEFINED_NVM_FLAG + CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_RADAR_DIAG_SOURCE_IP_SET2   = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET2 + CONST_USER_DEFINED_NVM_FLAG + CONST_DUMMY_BYTE 
CONST_WRITE_REQ_USERDEFINED_RADAR_DIAG_SOURCE_IP_SET3   = CONST_DID_WRITE_REQ_IP_ADDRESS + 10*CONST_DUMMY_BYTE + CONST_USER_DEFINED_DIAG_SOURCE_IP_ADDRESS_SET3 + CONST_USER_DEFINED_NVM_FLAG + CONST_DUMMY_BYTE
CONST_WRITE_REQ_DEFAULT_RADAR_DIAG_SOURCE_IP            = CONST_DID_WRITE_REQ_IP_ADDRESS + 10*CONST_DUMMY_BYTE + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE

CONST_WRITE_REQ_DEFAULT_RADAR_DOIP_ADDRESS              = CONST_DID_WRITE_REQ_DOIP_ADDRESS + CONST_DEFAULT_RADAR_DOIP_ADDRESS + 6*CONST_DUMMY_BYTE 
CONST_READ_RESP_DEFAULT_DOIP_ADDRESS                    = CONST_DID_READ_RESP_DOIP_ADDRESS + CONST_DEFAULT_RADAR_DOIP_ADDRESS + 6*CONST_DUMMY_BYTE 
CONST_WRITE_REQ_USERDEFINED_RADAR_DOIP_SET1             = CONST_DID_WRITE_REQ_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET1 + 6*CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_RADAR_DOIP_SET1             = CONST_DID_READ_RESP_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET1 + 6*CONST_DUMMY_BYTE
CONST_WRITE_REQ_USERDEFINED_RADAR_DOIP_SET2             = CONST_DID_WRITE_REQ_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET2 + 6*CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_RADAR_DOIP_SET2             = CONST_DID_READ_RESP_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET2 + 6*CONST_DUMMY_BYTE 
CONST_WRITE_REQ_USERDEFINED_RADAR_DOIP_SET3             = CONST_DID_WRITE_REQ_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET3 + 6*CONST_DUMMY_BYTE 
CONST_READ_RESP_USERDEFINED_RADAR_DOIP_SET3             = CONST_DID_READ_RESP_DOIP_ADDRESS + CONST_USER_DEFINED_RADAR_DOIP_ADDRESS_SET3 + 6*CONST_DUMMY_BYTE  


CONST_WRITE_REQ_USERDEFINED_IP_RANGE_1                  = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_1 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_1 + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_IP_RANGE_1                  = CONST_DID_READ_RESP_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_1 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_1 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE

CONST_WRITE_REQ_USERDEFINED_IP_RANGE_2                  = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_2 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_2 + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_IP_RANGE_2                  = CONST_DID_READ_RESP_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_2 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_2 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE

CONST_WRITE_REQ_USERDEFINED_IP_RANGE_3                  = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_3 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_3 + CONST_USER_DEFINED_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_IP_RANGE_3                  = CONST_DID_READ_RESP_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_3 + CONST_USER_DEFINED_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_3 + CONST_USER_DEFINED_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE

CONST_WRITE_REQ_USERDEFINED_IP_RANGE_4                  = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_4 + CONST_PREVIOUS_IP_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_4 + CONST_PREVIOUS_IP_NVM_FLAG + 6*CONST_DUMMY_BYTE

CONST_WRITE_REQ_USERDEFINED_IP_RANGE_5                  = CONST_DID_WRITE_REQ_IP_ADDRESS + CONST_USERDEFINED_RADAR_IP_RANGE_4 + CONST_DEFAULT_NVM_FLAG + CONST_USERDEFINED_REMOTE_IP_RANGE_4 + CONST_DEFAULT_NVM_FLAG + 6*CONST_DUMMY_BYTE
CONST_READ_RESP_USERDEFINED_IP_RANGE_5                  = CONST_DID_READ_RESP_IP_ADDRESS + CONST_DEFAULT_RADAR_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_REMOTE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DEFAULT_DIAG_SOURCE_IP_ADDRESS + CONST_DEFAULT_NVM_FLAG + CONST_DUMMY_BYTE
 