steps:
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'sc-ado-artifactory'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "zugspitze-series-generic-local/$(BRANCH_NAME)/$(COMMIT_ID)/binaries/ad_radar_sensor_app-0.0.1-1.x86_64.deb",
              "target": "$(Build.SourcesDirectory)/artifactorydownload/"
            }
          ]
        }
      failNoOp: true
    displayName: Download deb file
  
  - bash: |
      #sudo -S dpkg -i $(Build.SourcesDirectory)/artifactorydownload/$(BRANCH_NAME)/$(COMMIT_ID)/binaries/ad_radar_sensor_app-0.0.1-1.x86_64.deb 
      dpkg -x $(Build.SourcesDirectory)/artifactorydownload/$(BRANCH_NAME)/$(COMMIT_ID)/binaries/ad_radar_sensor_app-0.0.1-1.x86_64.deb ./
    displayName: install statepublisher debian package
      

