# -*- coding: utf-8 -*-

CONST_DIAG_SESSION_CNTRL_BOSCH_SESSION_REQ               ="1060"
CONST_DIAG_SESSION_CNTRL_EXTENDED_SESSION_REQ            ="1003"

CONST_DIAG_SESSION_CNTRL_DEFAULT_SESSION_RESP            ="5001"
CONST_DIAG_SESSION_CNTRL_EXTENDED_SESSION_RESP           ="5003"
CONST_DIAG_SESSION_CNTRL_BOSCH_SESSION_RESP              ="5060"

CONST_RESET_STATUS                                       ="0"

CONST_CLEAR_DTC_RESP                                     ="54"

CONST_SEPARATOR_CHARACTER                                = 59
CONST_APPEND_ZERO                                        = 0
CONST_USER_LENGTH_LESS_THAN_SEVEN                        = 7

#DTC's list

CONST_DTC_MASK                                           ="00"



DTC_DSP_UNDER_VOLTAGE                            ="510016"+CONST_DTC_MASK                    
DTC_DSP_OVER_VOLTAGE                             ="510017"+CONST_DTC_MASK               
DTC_SENSOR_RADAR_MODULATION                      ="510022"+CONST_DTC_MASK
DTC_DSP_ERROR_DETECTION                          ="510041"+CONST_DTC_MASK
DTC_SPU_SM_CTRL_STAT                             ="510047"+CONST_DTC_MASK
DTC_DSP_HW_FAILURE                               ="510049"+CONST_DTC_MASK
DTC_TEMPERATURE_TOO_HIGH                         ="51004b"+CONST_DTC_MASK
DTC_PLANT_FAILURE_DEFECT                         ="510055"+CONST_DTC_MASK
DTC_DSP_TIMEOUT_FAILURE                          ="510063"+CONST_DTC_MASK
DTC_DSP_INIT_SW_FAILURE                          ="510091"+CONST_DTC_MASK
DTC_DSP_SW_FAILURE                               ="510096"+CONST_DTC_MASK
DTC_HSSL_DRIVER_ERR                              ="510100"+CONST_DTC_MASK
DTC_HSSL_TIMEOUT_ERR                             ="510163"+CONST_DTC_MASK
DTC_DSP_INTERNAL_FAILURE                         ="510196"+CONST_DTC_MASK
DTC_XCS_WORKER_ERR                               ="510200"+CONST_DTC_MASK
DTC_XCS_TIMEOUT_ERR                              ="510263"+CONST_DTC_MASK
DTC_ETH_FAILURE                                  ="c02808"+CONST_DTC_MASK
DTC_ETH_ACCESS                                   ="c02908"+CONST_DTC_MASK
DTC_HW_FAILURE                                   ="d10064"+CONST_DTC_MASK
DTC_UC_PMS_EVRC_shortcut                         ="d60e00"+CONST_DTC_MASK
DTC_UC_CRITICAL_TRAP                             ="d60e04"+CONST_DTC_MASK
DTC_UC_UNDER_VOLTAGE                             ="d60e16"+CONST_DTC_MASK
DTC_UC_OVER_VOLTAGE                              ="d60e17"+CONST_DTC_MASK
DTC_UC_CONVCTRL_Failure                          ="d60e2f"+CONST_DTC_MASK
DTC_UC_MEMORY_FAILURE                            ="d60e42"+CONST_DTC_MASK
DTC_UC_PF_FAILURE                                ="d60e45"+CONST_DTC_MASK
DTC_UC_SAFETY_FAILURE                            ="d60e47"+CONST_DTC_MASK
DTC_RB_UC_InternalCommunication_Failure          ="d60e49"+CONST_DTC_MASK
DTC_UC_TEMP_RANGE                                ="d60e4b"+CONST_DTC_MASK
DTC_UC_CONFIG_FAILURE                            ="d60e55"+CONST_DTC_MASK
DTC_UC_VBAT_FAILURE_LOCKSTEP                     ="d60e62"+CONST_DTC_MASK
DTC_UC_TEMP_FAILURE                              ="d60e64"+CONST_DTC_MASK
DTC_UC_TRAP_FAILURE                              ="d60e68"+CONST_DTC_MASK
DTC_UC_SYNC_FAILURE                              ="d60e91"+CONST_DTC_MASK
DTC_UC_SAFE_STATE                                ="d60e93"+CONST_DTC_MASK
DTC_UC_OS_TRAP                                   ="d60e94"+CONST_DTC_MASK
DTC_UC_HW_BUS_FAILURE                            ="d60e96"+CONST_DTC_MASK
DTC_UC_SECURE_RADARBLK                           ="d60e97"+CONST_DTC_MASK
DTC_UC_EXT_UNDER_VOLTAGE                         ="d60f16"+CONST_DTC_MASK
DTC_UC_EXT_OVER_VOLTAGE                          ="d60f17"+CONST_DTC_MASK
DTC_UC_EXTERNAL_CLK_FAILURE                      ="d60f62"+CONST_DTC_MASK
DTC_UC_INTERNAL_CLK_FAILURE                      ="d60f96"+CONST_DTC_MASK
DTC_ASIC_UNDER_VOLTAGE                           ="dd0b16"+CONST_DTC_MASK  
DTC_ASIC_OVER_VOLTAGE                            ="dd0b17"+CONST_DTC_MASK
DTC_HW_WATCHDOG                                  ="dd0b47"+CONST_DTC_MASK
DTC_SPI_RX_TX_COM                                ="dd0b62"+CONST_DTC_MASK
DTC_CS520_EXT_CLOCK                              ="dd0b68"+CONST_DTC_MASK
DTC_CS520_MAX_RESTARTS                           ="dd0b91"+CONST_DTC_MASK
DTC_CS520_HW_BIST                                ="dd0b92"+CONST_DTC_MASK
DTC_ASIC_HW_FAILURE                              ="dd0b94"+CONST_DTC_MASK
DTC_HW_DISTURBED                                 ="dd0b96"+CONST_DTC_MASK
DTC_BAT_UNDER_VOLTAGE                            ="f00316"+CONST_DTC_MASK
DTC_BAT_OVER_VOLTAGE                             ="f00317"+CONST_DTC_MASK
DTC_L4_PDM_FAILURE                               ="f00318"+CONST_DTC_MASK

#Concating all DTC's
CONST_SUPPORTED_DTC = DTC_DSP_UNDER_VOLTAGE+DTC_DSP_OVER_VOLTAGE+DTC_SENSOR_RADAR_MODULATION+DTC_DSP_ERROR_DETECTION+DTC_SPU_SM_CTRL_STAT+DTC_DSP_HW_FAILURE+DTC_TEMPERATURE_TOO_HIGH+DTC_PLANT_FAILURE_DEFECT+\
                      DTC_DSP_TIMEOUT_FAILURE+DTC_DSP_INIT_SW_FAILURE+DTC_DSP_SW_FAILURE+DTC_HSSL_DRIVER_ERR+DTC_HSSL_TIMEOUT_ERR+DTC_DSP_INTERNAL_FAILURE+DTC_XCS_WORKER_ERR+DTC_XCS_TIMEOUT_ERR+DTC_ETH_FAILURE+\
					  DTC_ETH_ACCESS+DTC_HW_FAILURE+DTC_UC_PMS_EVRC_shortcut+DTC_UC_CRITICAL_TRAP+DTC_UC_UNDER_VOLTAGE+DTC_UC_OVER_VOLTAGE+DTC_UC_CONVCTRL_Failure+DTC_UC_MEMORY_FAILURE+DTC_UC_PF_FAILURE+DTC_UC_SAFETY_FAILURE+\
				      DTC_RB_UC_InternalCommunication_Failure+DTC_UC_TEMP_RANGE+DTC_UC_CONFIG_FAILURE+DTC_UC_VBAT_FAILURE_LOCKSTEP+DTC_UC_TEMP_FAILURE+DTC_UC_TRAP_FAILURE+DTC_UC_SYNC_FAILURE+DTC_UC_SAFE_STATE+DTC_UC_OS_TRAP+\
                      DTC_UC_HW_BUS_FAILURE+DTC_UC_SECURE_RADARBLK+DTC_UC_EXT_UNDER_VOLTAGE+DTC_UC_EXT_OVER_VOLTAGE+DTC_UC_EXTERNAL_CLK_FAILURE+DTC_UC_INTERNAL_CLK_FAILURE+DTC_ASIC_UNDER_VOLTAGE+DTC_ASIC_OVER_VOLTAGE+DTC_HW_WATCHDOG+\
                      DTC_SPI_RX_TX_COM+DTC_CS520_EXT_CLOCK+DTC_CS520_MAX_RESTARTS+DTC_CS520_HW_BIST+DTC_ASIC_HW_FAILURE+DTC_HW_DISTURBED+DTC_BAT_UNDER_VOLTAGE+DTC_BAT_OVER_VOLTAGE+DTC_L4_PDM_FAILURE					  
					

CONST_TESTER_PRESENT_RES                                ="7e00"

#Control DTC Setting
CONST_CONTROL_DTC_SETTING_ON_RES                        ="c501"
CONST_CONTROL_DTC_SETTING_OFF_RES                       ="c502"

# ECU Reset Response
CONST_ECU_HARD_RESET_RES                                ="5101"
CONST_ECU_SOFT_RESET_RES                                ="5103"

# UDS Service Identifiers
CONST_DIAG_UDS_SERVICE_WDBI                             = "2E"
CONST_DIAG_UDS_SERVICE_RDBI                             = "22"
CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP                    = "62"
CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP                    = "6e"

# UDS Subservice Identifiers
CONST_DIAG_UDS_SUBSERVICE_IP_ADDR                       = "0600"
CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR                      = "0601"
CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR                     = "0602"
CONST_DIAG_UDS_DID_MCS                                  = "060b"
CONST_DIAG_UDS_DID_MOUNTING_POSITION                    = "0500"
CONST_DIAG_UDS_DID_MEAS_PROGRAM                         = "060c"
CONST_DIAG_UDS_DID_MODULATION_CNTRL                     = "060e"
CONST_DIAG_UDS_DID_DESTINATION_PORT                     = "060d"
CONST_WRITE_DID_RES_MCS                                 = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_DID_MCS
CONST_READ_DID_RES_MCS                                  = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MCS
#swTest_checkMacIsWrittenToNvm
CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM1                = "01"
CONST_WRITE_DID_RES_MAC                                 = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_READ_DID_REQ_MAC                                  = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_READ_DID_RES_MAC                                  = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_WRITE_DID_RES_MAC_DATA                            = "4CDE16011056"
CONST_WRITE_DID_REQ_MAC_DATA                            = "8834FE000001"
CONST_WRITE_DID_RES_UNUSED                              ="00"
CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES1            ="00"
CONST_WRITE_RES_MAC_NVN_DATA                            =  CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR + CONST_WRITE_DID_RES_MAC_DATA + CONST_WRITE_DID_RES_UNUSED + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM1
CONST_WRITE_BCT_MAC_NVM_DATA                            =  CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR + CONST_WRITE_DID_REQ_MAC_DATA + CONST_WRITE_DID_RES_UNUSED +CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES1
#DiagFBL
CONST_WRITE_DID_RES_FBL_IP                              = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR
CONST_WRITE_DID_RES_FBL_MAC                             = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_WRITE_DID_RES_FBL_DOIP                             = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
CONST_READ_DID_REQ_FBL_IP                               = CONST_DIAG_UDS_SERVICE_RDBI+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR
CONST_READ_DID_RES_FBL_IP                                = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR
CONST_READ_DID_REQ_FBL_MAC                              = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_READ_DID_RES_FBL_MAC                              = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR
CONST_READ_DID_REQ_FBL_DOIP                             = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
CONST_READ_DID_RES_FBL_DOIP                             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
#swTest_checkResetMacAddressToBctConfig
CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES   ="00"
CONST_RESET_WRITE_MAC_TO_BCT                  = CONST_DIAG_UDS_SERVICE_WDBI+CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR+CONST_WRITE_DID_REQ_MAC_DATA+CONST_WRITE_DID_RES_UNUSED+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES
#swTest_checkMACAddress_requestoutofrange
CONST_DIAG_MAC_BYTE_LENGTH = 8
CONST_DIAG_MAC_REQUESTOUTOFRANGE_FF ="FF" * CONST_DIAG_MAC_BYTE_LENGTH
CONST_DIAG_MAC_REQUESTOUTOFRANGE_00 ="00" * CONST_DIAG_MAC_BYTE_LENGTH
CONST_DIAG_MAC_INVALID_NVM_FLAG ="8834FE0000010005"
CONST_DIAG_MAC_WRITE_REQUEST_OUT_OF_RANGE_FF_REQ = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR + CONST_DIAG_MAC_REQUESTOUTOFRANGE_FF
CONST_DIAG_MAC_WRITE_REQUEST_OUT_OF_RANGE_00_REQ = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR + CONST_DIAG_MAC_REQUESTOUTOFRANGE_00
CONST_DIAG_MAC_WRITE_REQUEST_OUT_OF_RANGE_NVM_INVALID_REQ = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_MAC_ADDR + CONST_DIAG_MAC_INVALID_NVM_FLAG

#swTest_checkDoIpIsWrittenToNvm
CONST_DIAG_DOIP_DUMMY                                   = "000000000000"
CONST_DIAG_USER_CONFIGURED_DOIP_ADDR1_HEX               = "1256"
CONST_DIAG_INITIAL_BCT_DOIP_ADDR                        = "1295"
CONST_DOIP_WRITE_TO_NVM                                 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR + CONST_DIAG_USER_CONFIGURED_DOIP_ADDR1_HEX + CONST_DIAG_DOIP_DUMMY
CONST_WRITE_DID_RES_DOIP                                = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
CONST_READ_DID_REQ_DOIP                                 = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
CONST_READ_DID_RES_DOIP                                 = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR
CONST_DOIP_BCT_TO_NVM                                   = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_DOIP_ADDR + CONST_DIAG_INITIAL_BCT_DOIP_ADDR + CONST_DIAG_DOIP_DUMMY
# Constants regarding IP Address Variant Handling Tests 
CONST_DIAG_INITIAL_BCT_IP_ADDR                          = "169.254.18.149"
CONST_DIAG_INITIAL_BCT_IP_ADDR_HEX                      = "A9FE1295"

CONST_DIAG_USER_CONFIGURED_IP_ADDR                      = "169.254.19.150"
CONST_DIAG_USER_CONFIGURED_IP_ADDR_HEX                  = "A9FE1396"

CONST_DIAG_USER_CONFIGURED_IP_ADDR2                     = "169.254.20.151"
CONST_DIAG_USER_CONFIGURED_IP_ADDR2_HEX                 = "A9FE1497"
CONST_WRITE_IP_RES                                      = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR
CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX                 = "A9FE2293"

CONST_DIAG_USER_CONFIGURED_IP_ADDR4_HEX                 = "A9FE559B"

CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX                 = "A9FE7464"

#Use one representative IP address
CONST_DEST_IP_ADDRESS_REP                               = "225.0.1.255"
#CONST_DEST_IP_ADDRESS_REP_HEX                           = "E10001FF"
CONST_DEST_IP_ADDRESS_REP_HEX                           = "e10001ff"

#Use one representative IP address :one of range 5
CONST_DEST_IP_ADDRESS_REP_RANGE5                        = "230.255.1.255"
CONST_DEST_IP_ADDRESS_REP_RANGE5_HEX                    ="E6FF01FF"

#Use one representative IP address :one of range 2
CONST_SRC_IP_ADDRESS_REP_RANGE2                         = "172.25.1.255"
CONST_SRC_IP_ADDRESS_REP_RANGE2_HEX                     ="AC1901FF"

#LGPSrcandLGPDestandDiagFromNVMIsWrittenToNvmForGivenRange1
CONST_LGP_SRC_RANGE1                                    ="0A030708" 
CONST_LGP_DEST_RANGE1                                   = "0A092238" 

#LGPSrcandLGPDestandDiagFromNVMIsWrittenToNvmForGivenRange2
CONST_LGP_SRC_RANGE2                                    = "AC137080"
CONST_LGP_DSET_RANGE2                                   = "AC192238"
 
#LGPSrcandLGPDestandDiagFromNVMIsWrittenToNvmForGivenRange3
CONST_LGPP_SRC_RANGE3                                   = "C0A80684"
CONST_LGP_SRC_RANGE3                                   = "C0A80386"
CONST_LGP_DSET_RANGE3                                  = "C0A86753"

CONST_LSP_SRC_BCT                                      = "C0A88757"

#change IP address service with Invalid max  Diag 
CONST_LGP_SRC_DIAG                                     = "C0A87865"
CONST_LGP_DEST_DIAG                                    = "C0A84563"
CONST_LGP_DIAG                                         ="A9FEFFFF"
CONST_LGP_DIAG_MIN                                     = "A9FE0000"
CONST_LGP_DEST_DIAG_MAX_RANGE3                         = "A9FF2293"

#change IP address for LGP Dest    
CONST_IP_LGP_SRC                                       ="0A235678"
CONST_IP_LGP_DEST                                      ="AC189234"

#change IP address sLGP Src
CONST_IP_sLGP_DST                                      = "C0A84321"

#swTest_reportNRC_requestchangeLGPSrcandusepreviuosconfigforLGPDest
CONST_IP_LGP_DEST_NRC                                  ="AC137865"

CONST_IP_LGP_DEST_NRC1                                 = "0A123215"

#swTest_InvalidLGPSrcandLGPDestisDifferentRange
CONST_IP_LGP_DST_INVALID                               = "0A078654"

#swTest_InvalidsecondbyteLGPDestForGivenRange3
CONST_INVALID_SEC_BYTE_LGP_SRC_RANGE3                  = "C0A80389"
CONST_INVALID_SEC_BYTE_LGP_DST_RANGE3                  = "C0F80708"


#swTest_InvalidsecondbyteLGPDestForGivenMinRange2
CONST_LGP_SER_GIVENMIN_RANGE2                          ="AC110389"
CONST_LGP_DEST_GIVENMIN_RANGE2                         ="AC070708"
CONST_LGP_DAG_GIVENMIN_RANGE2                          ="A9FE2293"
CONST_LGP_DEST_GIVENMAX_RANGE2                         ="AC3F0708"

#swTest_InvalidsecondbyteLGPSrcForGivenMinRange2
CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA ="00"
CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM = "01"
CONST_INVALIDSEC_LGPSRC_MINRANGE2_HEX           ="AC010389"
CONST_INVALIDSEC_LGPDST_MINRANGE2_HEX          ="AC140708"
CONST_INVALIDSEC_LGPSRC_MINRANGE2                      = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_INVALIDSEC_LGPSRC_MINRANGE2_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_INVALIDSEC_LGPDST_MINRANGE2_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_InvalidsecondbyteLGPSrcForGivenMaxRange2
CONST_INVALIDSEC_LGPSRC_MAXRANGE2_HEX             ="AC210389"
CONST_INVALIDSEC_LGPSRC_MAXRANGE2                       = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_INVALIDSEC_LGPSRC_MAXRANGE2_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_INVALIDSEC_LGPDST_MINRANGE2_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_InvalidsecondbyteLGPSrcForGivenRange3
CONST_LGP_SRC_GIVENSEC_RANGE3                          ="C0BC0389"
CONST_LGP_DEST_GIVENSEC_RANGE3                          ="C0A80708"
CONST_INVALIDSEC_LGPSRC_RANGE2                         = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_GIVENSEC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_GIVENSEC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_checkMacIsWrittenToNvm


#change IP address service with Invalid max Range3 LGP DestFirst Byte Diag 
CONST_LGP_DIAG_FIRST_RANGE3                          ="B9FE2293"

# used if e.g. only one of three possible IP addresses shall be coded
CONST_DIAG_IP_ADDR_REQUEST_ZERO                         = "00000000"

# used for cleaning up the NVM after every test case where it has been adapted
CONST_DIAG_CLEANUP_NVM_TO_INIT_BCT_IP_ADDR_VALUES       = "2E060000000000000000000000000000000000"


#swTest_reportNRC_requestchangeLGPDestandusepreviuosconfigforLGPSrc
#2E0600AC17864301AC18786501A9FE22930800
CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM  ="01"
CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST="02"
CONST_LGP_SRC_NRC = "AC178643"
CONST_LGP_DST_NRC = "AC187865"
CONST_LGP_DAG_NRC = "A9FE2293"
CONST_NVM_NRC = "08"
CONST_LGP_SRC_NRC_CHANGE ="C0A87865"
CONST_LGP_DST_NRC_CHANGE ="0A123215"
CONST_CHANGE_IP_LGP_SRC_DEST = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_NRC + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_NRC+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DAG_NRC + CONST_NVM_NRC + CONST_WRITE_DID_RES_UNUSED

#2E0600C0A87865020A12321501A9FE22930800 
#swTest_reportNRC_requestchangeLGPSrcandusepreviuosconfigforLGPDest
CONST_CHANGE_IP_LGP_TO_DEST = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_NRC_CHANGE + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGP_DST_NRC_CHANGE + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DAG_NRC + CONST_NVM_NRC + CONST_WRITE_DID_RES_UNUSED 

#swTest_PreviousUsedLGPSrcandLGPDestFromNVMIsWrittenToNvmForGivenRange1
CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST       ="02"
CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM           ="01"
CONST_LGPSRC_RANGE1                                = "0A080684"
CONST_LGPDEST_RANGE1                               = "0A556753"
CONST_LGPDOIP_RANGE1                               = "A9FE7464"
#CONST_PREV_LGP_SRC_NVM_RANGE1                      = CONST_DIAG_UDS_SERVICE_WDBI+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_LGPSRC_RANGE1+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGPDEST_RANGE1+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGPDOIP_RANGE1+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_WRITE_DID_RES_UNUSED
CONST_PREV_LGP_SRC_NVM_RANGE1                      = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDEST_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDOIP_RANGE1 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGPSRC_RES_RANGE1                            = "0A870684"
CONST_LGPDEST_RES_RANGE1                           = "0A456534"
#CONST_PREV_LGP_DST_NVM_RANGE1                      = CONST_DIAG_UDS_SERVICE_WDBI+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_LGPSRC_RES_RANGE1+CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGPDOIP_RANGE1+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_WRITE_DID_RES_UNUSED
CONST_PREV_LGP_DST_NVM_RANGE1                      = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_RES_RANGE1 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGPDEST_RES_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDOIP_RANGE1 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#swTest_PreviousUsedLGPSrcandLGPDestFromNVMIsWrittenToNvmForGivenRange2

CONST_LGP_SRC_NVM_RANGE2                          ="AC196674"
CONST_LGP_DEST_NVM_RANGE2                         = "AC1D3754"
CONST_PREV_LGP_SRC_NVM_RANGE2                     = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_NVM_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_NVM_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDOIP_RANGE1 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGP_DEST_RES_NVM_RANGE2                     = "AC1E3584"
CONST_PREV_LGP_DEST_NVM_RANGE2                    = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_NVM_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGP_DEST_RES_NVM_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDOIP_RANGE1 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

# swTest_LGPSrcFromNVMandPreviousUsedLGPDestIsWrittenToNvmForGivenRange1
CONST_LGPSRC_PREVDEST_NVM                         ="0A560694"
CONST_LGPDEST_PREVDEST_NVM                        ="0A351753"
CONST_LGPSRC_FROM_NVM_LGPDST_PREV_RANGE1              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_PREVDEST_NVM+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDEST_PREVDEST_NVM + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGPSRC_PREVDEST_WRITE_NVM                   ="0A270724"
#CONST_LGPDEST_RES_RANGE1
#CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX 
CONST_LGPSRC_FROM_NVM_LGPDST_PREV_RANGERES1            = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_PREVDEST_WRITE_NVM+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDEST_RES_RANGE1 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED


#swTest_LGPSrcFromNVMandPreviousUsedLGPDestIsWrittenToNvmForGivenRange2
CONST_LGP_SRC_PREV_RANGE2                           ="AC147805"
CONST_LGP_DEST_PREV_RANGE2                           ="AC194553"
CONST_LGP_SRC_PREV_RES_RANGE2                       ="AC124754"
CONST_LGP_SRC_PREV__RES_RANGE2                       ="AC156534"
CONST_LGPSRC_FROM_NVM_LGPDST_PREV_RANGE2 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_PREV_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_PREV_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGPSRC_FROM_NVM_LGPDST_PREV_RANGERES2 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_PREV_RES_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_SRC_PREV__RES_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#swTest_PreviousUsedLGPSrcLGPDestandDiagIsWrittenToNvm

CONST_PREVIOUSUSEDLGPSRCLGPDESTANDDIAGISWRITTENTONVM = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_PREV_RES_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGP_SRC_PREV__RES_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGPDOIP_RANGE1 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_WRITE_DID_RES_UNUSED


#swTest_InvalidMinLGPDestForGivenRange1
CONST_LGP_DST_DIAG                                    ="C0A80000"
CONST_INVALIDMINLGPDESTFORGIVENRANGE1                 =CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_WRITE_DID_RES_UNUSED
CONST_LGPSRC_DST_DIAG_RANGE2                          ="AC144567"
CONST_LGP_DST_DIAG_RANGE2                             ="AC100000"
CONST_INVALIDMINLGPDESTFORGIVENRANGE2                 =CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGPSRC_DST_DIAG_RANGE3                          = "0A010389"
CONST_LGP_DST_DIAG_RANGE3                             = "0A000000"
CONST_INVALIDMINLGPDESTFORGIVENRANGE3                 =CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#InvalidMaxLGPSrcForGivenRange1
CONST_LGP_DEST_RANGE1_INVALID                        ="0AFFFFFF" 
CONST_INVALIDMAXLGPSRCFORGIVENRANGE1                 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_INVALIDMAXLGPSRCFORGIVENRANGE2                 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_INVALIDMAXLGPSRCFORGIVENRANGE3                 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#InvalidMinLGPSrcForGivenRange1
CONST_LGP_MIN_RANGE1_INVALID                      = "AC1FFFFF"
CONST_INVALIDMINLGPSRCFORGIVENRANGE1              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_LGPDST_MIN_RANGE1_INVALID                      = "AC190708"
CONST_INVALIDMINLGPSRCFORGIVENRANGE2              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGPDST_MIN_RANGE1_INVALID + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_INVALIDMINLGPSRCFORGIVENRANGE3              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_DST_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_GIVENSEC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#InvalidMaxLGPDestForGivenRange1
CONST_INVALIDMAXLGPDESTFORGIVENRANGE1                = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_RANGE1_INVALID + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_INVALIDMAXLGPDESTFORGIVENRANGE2                = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPSRC_DST_DIAG_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_MIN_RANGE1_INVALID + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED
CONST_MAX_LGP_DEST_RANGE1                            = "C0A8FFFF"
CONST_INVALIDMAXLGPDESTFORGIVENRANGE3                = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_MAX_LGP_DEST_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_WRITE_DID_RES_UNUSED

#PreviousUsedLGPSrcandLGPDestIsWrittenToNvm
COSNT_PREVIOUSUSEDLGPSRCANDLGPDESTISWRITTENTONVM        = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_PREV_RES_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGP_SRC_PREV__RES_RANGE2 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_WRITE_DID_RES_UNUSED

#swTest_LGPSrcandLGPDestandDiagFromNVMIsWrittenToNvmForGivenRange1
CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA ="00"
CONST_LGPSRC_RANGE = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_RANGE1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
CONST_LGPDST_RANGE2 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DSET_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR4_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
CONST_LGPSRC_RANGE3 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DSET_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_LGPSrcFromNVMandLGPDestandDIAGFromBCTIsWrittenToNvm
CONST_LGPSRC_BCT = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DSET_RANGE3 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

CONST_LGPDST = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_LGP_DSET_RANGE3 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_USER_CONFIGURED_IP_ADDR4_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#2E0600C0A8068400C0A8875701A9FE74640000
CONST_LGPSRC_BCTDST = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGPP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_LSP_SRC_BCT + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR5_HEX+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_LGPSrcFromBCTandPreviousUsedLGPDestIsWrittenToNvm

CONST_LGPDEST = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_LGP_DSET_RANGE3 + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_DIAG_USER_CONFIGURED_IP_ADDR4_HEX+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES+CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidLGPSrcandLGPDestisEqual
CONST_LGP_DEST_NVM_INVALID="08"
CONST_DESTIS = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX+CONST_LGP_DEST_NVM_INVALID+CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_reportNRC_requestchangeLGPSrcandusepreviuosconfigforLGPDest

CONST_REPORT_NRC    = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_IP_LGP_DEST_NRC1 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_LGP_DEST_NVM_INVALID + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
CONST_REPORT_NRC_RES = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_IP_LGP_DEST_NRC + CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_LGP_DEST_NVM_INVALID + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_reportNRC_requestchangeLGPSrcandusepredefinedvaluesforLGPDest
CONST_REPORT_NRC_PREDEFINED = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_IP_LGP_SRC+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_IP_sLGP_DST+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_LGP_DEST_NVM_INVALID + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_reportNRC_requestchangeLGPDestandusepredefinedvaluesforLGPSrc
CONST_REPORT_NRC_PREDEFINEDLGP  = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_IP_LGP_SRC+CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_IP_LGP_DEST+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_LGP_DEST_NVM_INVALID + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidFirstByteDiag
CONST_INVALID_FIRST_DIAG = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DIAG_FIRST_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidSecondByteDiag
CONST_INVALID_SEC_DIAG =CONST_DIAG_UDS_SERVICE_WDBI+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DEST_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DEST_DIAG_MAX_RANGE3+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidMinDiag
CONST_MINDIAG = CONST_DIAG_UDS_SERVICE_WDBI+CONST_DIAG_UDS_SUBSERVICE_IP_ADDR+CONST_LGP_SRC_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DEST_DIAG+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DIAG_MIN+CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidMaxDiag
CONST_MAXDIAG = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SRC_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DEST_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_LGP_DIAG + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA

#swTest_InvalidsecondbyteLGPDestForGivenMaxRange2
#2E0600AC11038901AC3F070801A9FE22930000
CONST_INVALIDSECBYTE_MAXRANGE2 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SER_GIVENMIN_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DEST_GIVENMAX_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_InvalidsecondbyteLGPDestForGivenMinRange2
#2E0600AC11038901AC07070801A9FE22930000
CONST_INVALIDSECBYTE_MINRANE2 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_LGP_SER_GIVENMIN_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_LGP_DEST_GIVENMIN_RANGE2 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#swTest_InvalidsecondbyteLGPDestForGivenRange3
#2E0600C0A8038901C0F8070801A9FE22930000
CONST_INVALIDSECBYTE_RANGE3  = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_SUBSERVICE_IP_ADDR + CONST_INVALID_SEC_BYTE_LGP_SRC_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM+CONST_INVALID_SEC_BYTE_LGP_DST_RANGE3 + CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM + CONST_DIAG_USER_CONFIGURED_IP_ADDR3_HEX + CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES + CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA
#Constants regarding MAC Address Variant Handling Tests
CONST_DIAG_INITIAL_BCT_MAC_ADDR                         = "88:34:fe:00:00:01"
CONST_DIAG_USER_CONFIGURED_MAC_ADDR                     = "4c:de:16:01:10:ff"
CONST_DIAG_USER_CONFIGURED_MAC_ADDR1                    = "4c:de:16:01:10:56"

# Constants regarding DoIP Target Address Variant Handling Tests
CONST_DIAG_INITIAL_BCT_DOIP_ADDR                        = "1295"
CONST_DIAG_USER_CONFIGURED_DOIP_ADDR_HEX                = "1396"
CONST_DIAG_USER_CONFIGURED_DOIP_ADDR1_HEX               = "1256"
CONST_DIAG_DOIP_DUMMY                                   = "000000000000"
CONST_DIAG_DOIP_NVM_NOT_CONFIGURED                      = "0000"

# Variant Handling Service Dummy Flags
CONST_DIAG_VAR_HDL_SERVICE_DUMMY_DATA                   = "00"

# NVM Flag Constants
CONST_DIAG_NVM_FLAG_READ_INITIAL_BCT_VALUES             = "00"
CONST_DIAG_NVM_FLAG_READ_VALUES_FROM_NVM                = "01"
CONST_DIAG_NVM_FLAG_IGNORE_ADDR_FROM_REQUEST            = "02"
CONST_LGP_DEST_NVM_INVALID                              = "08"

# Constants regarding Diagnostic Session Control: Jump to Programming Session / Back to Application Software Tests
CONST_DIAG_RESET_REASON_NOTHING                         = 0
CONST_DIAG_DSC_RESPONSE_PENDING                         = "7f1078"

# Constants regarding IP Address Variant Handling Tests 
CONST_DIAG_USER_CONFIGURED_IP_ADDR3                     = "169.254.34.147"
CONST_DIAG_USER_CONFIGURED_IP_ADDR4                     = "169.254.85.155"
CONST_DIAG_USER_CONFIGURED_IP_ADDR5                     = "169.254.116.100"
CONST_LGP_SRC_RANGE1_IP                                 = "10.3.7.8"
CONST_LGP_DST_RANGE1_IP                                 = "10.9.34.56"
CONST_LGP_SRC_RANGE2_IP                                 = "172.19.112.128"
CONST_LGP_DST_RANGE2_IP                                 = "172.25.34.56"
CONST_LGP_SRC_RANGE3_IP                                 = "192.168.3.134"
CONST_LGP_DST_RANGE3_IP                                 = "192.168.103.83"
CONST_LGP_DST_RANGE1_IP1                                = "10.69.101.52"
CONST_LGP_SRC_RANGE1_IP2                                = "10.39.7.36"
CONST_LGP_DST_RANGE2_IP1                                = "172.30.53.132"
CONST_LGP_SRC_RANGE2_IP2                                = "172.18.71.84"
CONST_LGP_SRC_RANGE3_IP1                                = "192.168.6.132"
CONST_LGP_DST_RANGE3_IP1                                = "192.168.135.87"
CONST_BCT_DEFAULT_VALUE                                 = "169.254.18.149"
CONST_LGP_SRC_INITIAL_BCT_IP_ADDR_HEX                   = "c0a82833"
CONST_LGP_DEST_INITIAL_BCT_IP_ADDR_HEX                  = "c0a82802"
CONST_DIAG_INITIAL_BCT_IP_ADDR_HEX                      = "a9fe1295"
CONST_LGP_SRC_DEFAULT                                   ="192.168.40.51"
CONST_LGP_DST_DEFAULT                                   ="192.168.40.2"
CONST_READ_DID_RES_IP                                   = "620600"
CONST_WRITE_DID_RES_IP                                  = "6e0600"
CONST_OUT_OF_RANGE_NRC                                  = "7f2e31"

# IP address variant coding
USE_PRE_DEFINED_IP_FLAG_WRITE_REQUEST                   = "00"
USE_REQUEST_IP_FLAG_WRITE_REQUEST                       = "01"
USE_CURRENT_IP_FLAG_WRITE_REQUEST                       = "02"
USE_CURRENT_IP_FLAG_READ_REQUEST                        = "220600"

# Constants for Destination port address
CONST_USER_CONFIG_DESTN_PORT                            = "0600"
CONST_BCT_CONFIG_DESTN_PORT                             = "76c0"
CONST_READ_DID_RES_DESTN_PORT                           = "62060d"
       
#Default Data Value for the DID
CONST_DEFAULT_DATA_VALUE_DID                            = "ff"

# Constants for ECU Hardware Version Number
CONST_DID_HW_SAMPLE_VERSION                             = "ef13"
# The ECU Hardware Version Read DID Request
CONST_READ_DID_HW_VERSION_REQUEST                       = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_HW_SAMPLE_VERSION
# Length of DID HW Sample Version in Bytes
CONST_HW_VERSION_DID_LENGTH_IN_BYTES                    =  13
# The DID responds with 13 bytes of Data
CONST_DID_HW_SAMPLE_DATA_VALUE                          = CONST_DEFAULT_DATA_VALUE_DID * CONST_HW_VERSION_DID_LENGTH_IN_BYTES
# DID Response of 13 bytes for HW Sample Version
CONST_ECU_HARDWARE_VERSION_DID_RESP                     = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_HW_SAMPLE_VERSION + CONST_DID_HW_SAMPLE_DATA_VALUE


# Constants for ECU Serial Number
CONST_DID_ECU_SERIAL_NUMBER                             = "f18c"
# The ECU Serial Number Read DID Request
CONST_READ_DID_ECU_SERIAL_NUMBER_REQUEST                = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_ECU_SERIAL_NUMBER
# Length of DID ECU Serial Number in Bytes
CONST_SERIAL_NUMBER_DID_LENGTH_IN_BYTES                 =  40                      
# ECU Serial Number is 40 Bytes of Data
CONST_DID_ECU_SERIAL_NUMBER_DATA_VALUE                  = "ff"*CONST_SERIAL_NUMBER_DID_LENGTH_IN_BYTES
# DID Response of 40 bytes for Serial Number
CONST_ECU_SERIAL_NUMBER_DID_RESP                        =  CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_ECU_SERIAL_NUMBER + CONST_DID_ECU_SERIAL_NUMBER_DATA_VALUE
                                                                  
                                                                                                                                                                                                           
# Constants for ECU Manufacturing Date
CONST_DID_ECU_MANUFACTURING_DATA                        = "f18b"
# The ECU Manufacturing Data Read DID Request
CONST_READ_DID_ECU_MANUFACTURING_DATA_REQUEST           = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_ECU_MANUFACTURING_DATA
# Length of ECU Manufacturing Year in Bytes
CONST_ECU_MANUFACTURING_YEAR_LENGTH_IN_BYTES            =  4
CONST_ECU_MANUFACTURING_YEAR_DATA                       = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_YEAR_LENGTH_IN_BYTES
# Length of ECU Manufacturing Month in Bytes
CONST_ECU_MANUFACTURING_MONTH_LENGTH_IN_BYTES           =  2
CONST_ECU_MANUFACTURING_MONTH_DATA                      = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_MONTH_LENGTH_IN_BYTES
# Length of ECU Manufacturing Day in Bytes
CONST_ECU_MANUFACTURING_DAY_LENGTH_IN_BYTES             =  2
CONST_ECU_MANUFACTURING_DAY_DATA                        = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_DAY_LENGTH_IN_BYTES
# Length of ECU Manufacturing Day of year in Bytes
CONST_ECU_MANUFACTURING_DAY_OF_YEAR_LENGTH_IN_BYTES     =  3
CONST_ECU_MANUFACTURING_DAY_OF_YEAR_DATA                = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_DAY_OF_YEAR_LENGTH_IN_BYTES
# Length of ECU Manufacturing Hour in Bytes
CONST_ECU_MANUFACTURING_HOUR_LENGTH_IN_BYTES            =  2
CONST_ECU_MANUFACTURING_HOUR_DATA                       = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_HOUR_LENGTH_IN_BYTES
# Length of ECU Manufacturing Minutes in Bytes
CONST_ECU_MANUFACTURING_MINUTES_LENGTH_IN_BYTES         =  2
CONST_ECU_MANUFACTURING_MINUTES_DATA                    = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_MINUTES_LENGTH_IN_BYTES
# Length of ECU Manufacturing Seconds in Bytes
CONST_ECU_MANUFACTURING_SECONDS_LENGTH_IN_BYTES         =  2
CONST_ECU_MANUFACTURING_SECONDS_DATA                    = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_MANUFACTURING_SECONDS_LENGTH_IN_BYTES

# DID Response of 17 bytes for ECU Manufacturing Data
CONST_ECU_MANUFACTURING_DATE_DID_RESP                   = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_ECU_MANUFACTURING_DATA + CONST_ECU_MANUFACTURING_YEAR_DATA +\
                                                           CONST_ECU_MANUFACTURING_MONTH_DATA + CONST_ECU_MANUFACTURING_DAY_DATA + CONST_ECU_MANUFACTURING_DAY_OF_YEAR_DATA +\
                                                               CONST_ECU_MANUFACTURING_HOUR_DATA + CONST_ECU_MANUFACTURING_MINUTES_DATA + CONST_ECU_MANUFACTURING_SECONDS_DATA
                                                                   
# Constants for ECU Plant Container Number
CONST_DID_ECU_PLANT_CONTAINER_NUMBER                    = "ef16"
# The ECU Plant Container Number Read DID Request
CONST_READ_DID_PLANT_CONTAINER_NUMBER_REQUEST           = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_ECU_PLANT_CONTAINER_NUMBER
# Length of Plant Container Data in Bytes
CONST_ECU_PLANT_CONTAINER_LENGTH_IN_BYTES               =  10
# Plant Container Number is 10 bytes of Data
CONST_DID_ECU_PLANT_CONTAINER_DATA_VALUE                = CONST_DEFAULT_DATA_VALUE_DID * CONST_ECU_PLANT_CONTAINER_LENGTH_IN_BYTES
# DID Response of 10 bytes of Plant Container Data
CONST_ECU_PLANT_CONTAINER_NUMBER_DID_RESP               = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_ECU_PLANT_CONTAINER_NUMBER + CONST_DID_ECU_PLANT_CONTAINER_DATA_VALUE


# Constants for Customer Software Version
CONST_DID_CUSTOMER_SW_VERSION_NUMBER                    = "f189"
# The Customer SW Version Number Read DID Request
CONST_READ_DID_CUSTOMER_SW_VERSION_REQUEST              = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_CUSTOMER_SW_VERSION_NUMBER
# Constants for Customer Software Version
CONST_SPACE_SW_VERSION_ENCODED_DATA                     = "30202020202020" 
# DID Response 24 bytes for Customer SW Version                                                         
CONST_CUSTOMER_SOFTWARE_VERSION_DID_RESP                = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_CUSTOMER_SW_VERSION_NUMBER


# Constants for System Supplier Identification
CONST_DID_SYSTEM_SUPPLIER_IDENTIFICATION                = "f187"
# The Supplier Identification Read DID Request
CONST_READ_DID_SUPPLIER_IDENTIFICATION_REQUEST          = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_SYSTEM_SUPPLIER_IDENTIFICATION
# Supplier Identification is of 10 bytes data
# Supplier Identification encoded in ASCII "BOSCH     "
CONST_SUPPLIER_IDENTIFICATION_ENCODED_DATA              = "424f5343482020202020"
# DID Response of 10 bytes for Supplier Identification
CONST_SUPPLIER_IDENTIFICATION_DID_RESP                  = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_SYSTEM_SUPPLIER_IDENTIFICATION + CONST_SUPPLIER_IDENTIFICATION_ENCODED_DATA
# Constants for Application SW Version Number
CONST_DID_APP_SW_VERSION_NUMBER                         = "f195"     
# The Application SW Version Read DID Request
CONST_READ_DID_APP_SW_VERSION_REQUEST                   = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_APP_SW_VERSION_NUMBER
# Constants for Major,Minor and Patch Version    
CONST_ECU_APP_SW_MAJOR_VERSION                          = "0b"
CONST_ECU_APP_SW_MINOR_VERSION                          = "00"
CONST_ECU_APP_SW_PATCH_NUMBER                           = "00"
# DID Response of 3 bytes for App SW version 
CONST_ECU_APPLICATION_SW_VERSION_DID_RESP               = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_APP_SW_VERSION_NUMBER + CONST_ECU_APP_SW_MAJOR_VERSION + CONST_ECU_APP_SW_MINOR_VERSION+CONST_ECU_APP_SW_PATCH_NUMBER

# Constants for Boot SW Version Number
CONST_DID_BOOT_SW_VERSION_NUMBER                        = "f197"  
# The Boot SW Version Read DID Request
CONST_READ_DID_BOOT_SW_VERSION_REQUEST                   = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_BOOT_SW_VERSION_NUMBER
# Constants for Major,Minor and Patch Version                  
CONST_ECU_BOOT_SW_MAJOR_VERSION                         = "01"
CONST_ECU_BOOT_SW_MINOR_VERSION                         = "02"
CONST_ECU_BOOT_SW_PATCH_NUMBER                          = "00"
# DID Response of 3 bytes for Boot SW version
CONST_ECU_BOOT_SOFTWARE_VERSION_DID_RESP                = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_BOOT_SW_VERSION_NUMBER + CONST_ECU_BOOT_SW_MAJOR_VERSION + CONST_ECU_BOOT_SW_MINOR_VERSION+CONST_ECU_BOOT_SW_PATCH_NUMBER

# Constants for Debug Data Identifier Default Value
CONST_DEBUG_DATA_IDENTIFIER_DEFAULT_VALUE               = "00"

# Constants for Software Trap Information Data Identifier
CONST_SOFTWARE_TRAP_INFORMATION_DATA_LENGTH_IN_BYTES    = 208
CONST_SOFTWARE_TRAP_INFORMATION_DEFAULT_DATA            = CONST_DEBUG_DATA_IDENTIFIER_DEFAULT_VALUE * CONST_SOFTWARE_TRAP_INFORMATION_DATA_LENGTH_IN_BYTES
# The Software Trap Information Read DID Request Number
CONST_DID_SOFTWARE_TRAP_INFORMATION                     = "fdff"
# The Software Trap Information Read DID Request
CONST_READ_DID_SOFTWARE_TRAP_INFORMATION_REQUEST        = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_SOFTWARE_TRAP_INFORMATION
# DID Response of 208 bytes for Software Trap Information
CONST_SOFTWARE_TRAP_INFORMATION_DID_RESPONSE            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_SOFTWARE_TRAP_INFORMATION + CONST_SOFTWARE_TRAP_INFORMATION_DEFAULT_DATA

# Constants for OS Exception Log Data Identifier
CONST_OS_EXCEPTION_INFORMATION_LENGTH_IN_BYTES          = 396
CONST_OS_EXCEPTION_INFORMATION_DEFAULT_DATA             = CONST_DEBUG_DATA_IDENTIFIER_DEFAULT_VALUE * CONST_OS_EXCEPTION_INFORMATION_LENGTH_IN_BYTES
# The OS Exception Log Read DID Request Number
CONST_DID_OS_EXCEPTION_INFORMATION                      = "fdfa"
# The OS Exception Log Read DID Request
CONST_READ_DID_OS_EXCEPTION_INFORMATION_REQUEST         = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_OS_EXCEPTION_INFORMATION
# DID Response of 396 bytes for OS Exception Log
CONST_OS_EXCEPTION_INFORMATION_DID_RESPONSE             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_OS_EXCEPTION_INFORMATION + CONST_OS_EXCEPTION_INFORMATION_DEFAULT_DATA


# Constants for SMU Alarm Information Data Identifier
CONST_SMU_ALARM_INFORMATION_DATA_LENGTH_IN_BYTES        = 20
CONST_SMU_ALARM_INFORMATION_DEFAULT_DATA                = CONST_DEBUG_DATA_IDENTIFIER_DEFAULT_VALUE*CONST_SMU_ALARM_INFORMATION_DATA_LENGTH_IN_BYTES
# The SMU Alarm Information Read DID Request Number
CONST_DID_SMU_ALARM_INFORMATION                         = "fdfb"
# The SMU Alarm Information Read DID Request
CONST_READ_DID_SMU_ALARM_INFORMATION_REQUEST            = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DID_SMU_ALARM_INFORMATION
# DID Response of 20 bytes for SMU Alarm Information
CONST_SMU_ALARM_INFORMATION_DID_RESPONSE                = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DID_SMU_ALARM_INFORMATION + CONST_SMU_ALARM_INFORMATION_DEFAULT_DATA

#MCS constants
CONST_TIME_SLOT_SYNCHTYPE                               = "01"
CONST_INTERLEAVED_SYNCHTYPE                             = "02"

CONST_SYNCHTYPE_NO_SYNCHTYPE_FROM_PDU                    = "00"

CONST_SENSORTIME_OFFSET                                 = "33556677"
CONST_SENSORTIME_OFFSET1                                = "88993345"
CONST_SENSORTIME_OFFSET2                                = "FFFFFFFF"

CONST_SENSORTIME_OFFSET_FROM_PDU                        = "00000000"

CONST_MCS_SELECTOR_DIAG                                 = "00"
CONST_MCS_SELECTOR_PDU                                  = "01"
CONST_MCS_WRONG_SELECTOR                                = "02"

CONST_MCS_DUMMY                                         = "0000"

CONST_DIAG_UDS_WDBI_MCS_REQUEST_MCS_SELECTOR_DIAG       = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MCS + CONST_TIME_SLOT_SYNCHTYPE + CONST_SENSORTIME_OFFSET + CONST_MCS_DUMMY + CONST_MCS_SELECTOR_DIAG
CONST_DIAG_UDS_WDBI_MCS_REQUEST_MCS_SELECTOR_PDU        = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MCS + CONST_TIME_SLOT_SYNCHTYPE + CONST_SENSORTIME_OFFSET1 + CONST_MCS_DUMMY + CONST_MCS_SELECTOR_PDU

CONST_DIAG_UDS_WDBI_MCS_REQUEST_MCS_SELECTOR_WRONG      = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MCS + CONST_INTERLEAVED_SYNCHTYPE + CONST_SENSORTIME_OFFSET2 + CONST_MCS_DUMMY+CONST_MCS_WRONG_SELECTOR

CONST_DIAG_UDS_RDBI_MCS_REQUEST                         = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_DID_MCS

CONST_DIAG_UDS_DID_DMP00                                = "0000"
CONST_DIAG_UDS_DID_DMP01                                = "0001"
CONST_DIAG_UDS_DID_DMP02                                = "0002"
CONST_DIAG_UDS_DID_DMP04                                = "0004"
CONST_DIAG_UDS_DID_DMP05                                = "0005"

CONST_DIAG_UDS_DID_DMP_SELECTOR_0                       = "00"
CONST_DIAG_UDS_DID_DMP_SELECTOR_1                       = "01"

CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE           = "ffff"
CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1         = "0041"
CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2         = "0073"

CONST_DIAG_UDS_DID_DMP_30KPH_VELOCITY_RANGE_1           = "001e"
CONST_DIAG_UDS_DID_DMP_60KPH_VELOCITY_RANGE_2           = "003c"

CONST_DIAG_UDS_DID_DMP05_100KPH_VELOCITY_RANGE_1        = "0064"
CONST_DIAG_UDS_DID_DMP05_150KPH_VELOCITY_RANGE_2        = "0096"

CONST_DIAG_UDS_DID_DMP05_90KPH_VELOCITY_RANGE_1         = "005a"

CONST_DIAG_UDS_DID_DMP_RESERVED                         = "00"

# Constants for Measurement Program DID Data
CONST_DIAG_UDS_READ_DID_RESP_DMP00                      = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP00 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP04                      = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP04 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP01_65_115KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP01 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP01_30_60KPH             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP01 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_30KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_60KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP02_30_60KPH             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP02 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_30KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_60KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP02_65_115KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP02 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP05_30_60KPH             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP05 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_30KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_60KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP05_100_150KPH           = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP05 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP05_100KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP05_150KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP05_65_115KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP05 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_WRITE_DID_REQ_DMP05_65_115KPH            = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP05 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_WRITE_DID_REQ_DMP00                      = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP00 + CONST_DIAG_UDS_DID_DMP_SELECTOR_0 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_WRITE_RESP_DMP                           = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP+CONST_DIAG_UDS_DID_MEAS_PROGRAM
CONST_DIAG_UDS_READ_RESP_DMP                            = CONST_DIAG_UDS_SERVICE_RDBI+CONST_DIAG_UDS_DID_MEAS_PROGRAM

# Constants for Measurement Program PDU Data
CONST_DIAG_UDS_READ_DID_RESP_DMP00_SELECTOR_1           = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP00 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP01_SELECTOR_1           = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP01 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP02_SELECTOR_1           = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP02 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP04_SELECTOR_1           = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP04 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_DEFAULT_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED

CONST_DIAG_UDS_READ_DID_RESP_DMP00_30_60KPH             = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP00 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP_30KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP_60KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP01_90_150KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP01 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP05_90KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP05_150KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP02_90_150KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP02 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP05_90KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP05_150KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED
CONST_DIAG_UDS_READ_DID_RESP_DMP04_90_150KPH            = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MEAS_PROGRAM + CONST_DIAG_UDS_DID_DMP04 + CONST_DIAG_UDS_DID_DMP_SELECTOR_1 + CONST_DIAG_UDS_DID_DMP05_90KPH_VELOCITY_RANGE_1 + CONST_DIAG_UDS_DID_DMP05_150KPH_VELOCITY_RANGE_2 + CONST_DIAG_UDS_DID_DMP_RESERVED

#constants for Modulation control using Diag
CONST_MODULATION_CNTRL_START_MODULATION                 ="01"
CONST_MODULATION_CNTRL_STOP_MODULATION                  ="02"
CONST_MODULATION_CNTRL_WRONG_MODULATION                 ="03"
CONST_WRITE_DID_RES_MODULATION_CNTRL                    = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_DID_MODULATION_CNTRL
CONST_READ_DID_RES_MODULATION_CNTRL                     = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MODULATION_CNTRL

CONST_WRITE_DID_REQ_START_MODULATION                    = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MODULATION_CNTRL + CONST_MODULATION_CNTRL_START_MODULATION
CONST_WRITE_DID_REQ_STOP_MODULATION                    = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MODULATION_CNTRL + CONST_MODULATION_CNTRL_STOP_MODULATION
CONST_WRITE_DID_REQ_WRONG_MODULATION_VALUE              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MODULATION_CNTRL + CONST_MODULATION_CNTRL_WRONG_MODULATION

#constans for mounting position parameters
CONST_SENSOR_POS_X                                     = "1500" 
CONST_SENSOR_POS_Y                                     = "1200"
CONST_SENSOR_POS_Z                                     = "1800"
CONST_SENSOR_AZIMUTH                                   = "7C56"     
CONST_SENSOR_ELEVATION                                 = "0A67"   
CONST_SENSROR_ORIENTATION                              = "02"    

CONST_INVALID_SENSOR_POS_X                             = "7000" 
CONST_INVALID_SENSOR_POS_Y                             = "8000" 
CONST_INVALID_SENSOR_POS_Z                             = "9000"
CONST_INVALID_SENSOR_AZIMUTH                           = "CF89"
CONST_INVALID_SENSOR_ELEVATION                         = "CD89"
CONST_INVALID_SENSOR_ORIENTATION                       = "03"

CONST_WRITE_DID_REQ_MOUNTING_POSITION                  = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MOUNTING_POSITION + CONST_SENSOR_POS_X + CONST_SENSOR_POS_Y + CONST_SENSOR_POS_Z + CONST_SENSOR_AZIMUTH + CONST_SENSOR_ELEVATION + CONST_SENSROR_ORIENTATION
CONST_READ_DID_REQ_MOUNTING_POSITION                   = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_DID_MOUNTING_POSITION

CONST_WRITE_DID_RES_MOUNTING_POSITION                  = CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_DID_MOUNTING_POSITION
CONST_READ_DID_RES_MOUNTING_POSITION                   = CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_MOUNTING_POSITION

CONST_WRITE_DID_REQ_MOUNTING_POSITION1                 = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_MOUNTING_POSITION + CONST_INVALID_SENSOR_POS_X + CONST_INVALID_SENSOR_POS_Y + CONST_INVALID_SENSOR_POS_Z + CONST_INVALID_SENSOR_AZIMUTH + CONST_INVALID_SENSOR_ELEVATION + CONST_INVALID_SENSOR_ORIENTATION

CONST_DESTINATION_PORT_NUMBER                          = "0800"
CONST_DESTINATION_PORT_RESERVED                        = "0000000000"
CONST_DESTINATION_PORT_RESERVED1                        ="00000000000000"
CONST_USE_DESTINATION_PORT_FROM_NVM                    = "01"
CONST_USE_DESTINATION_PORT_FROM_BCT                    = "00"
CONST_INVALID_DESTINATION_PORT_NUMBER_MIN              = "0300"
CONST_INVALID_DESTINATION_PORT_NUMBER_MAX              = "ffff"


CONST_WRITE_DID_REQ_DESTINATION_PORT_NVM               = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_DESTINATION_PORT + CONST_DESTINATION_PORT_NUMBER + CONST_DESTINATION_PORT_RESERVED+ CONST_USE_DESTINATION_PORT_FROM_NVM
CONST_READ_DID_REQ_DESTINATION_PORT                    = CONST_DIAG_UDS_SERVICE_RDBI + CONST_DIAG_UDS_DID_DESTINATION_PORT

CONST_WRITE_DID_RES_DESTINATION_PORT                   =  CONST_DIAG_UDS_SERVICE_WDBI_POS_RESP + CONST_DIAG_UDS_DID_DESTINATION_PORT
CONST_READ_DID_RES_DESTINATION_PORT                    =  CONST_DIAG_UDS_SERVICE_RDBI_POS_RESP + CONST_DIAG_UDS_DID_DESTINATION_PORT

CONST_WRITE_DID_REQ_DESTINATION_PORT_BCT               = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_DESTINATION_PORT + CONST_DESTINATION_PORT_RESERVED1 + CONST_USE_DESTINATION_PORT_FROM_BCT

CONST_WRITE_DID_REQ_DESTINATION_PORT_NVM1              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_DESTINATION_PORT + CONST_INVALID_DESTINATION_PORT_NUMBER_MIN + CONST_DESTINATION_PORT_RESERVED+ CONST_USE_DESTINATION_PORT_FROM_NVM

CONST_WRITE_DID_REQ_DESTINATION_PORT_NVM2              = CONST_DIAG_UDS_SERVICE_WDBI + CONST_DIAG_UDS_DID_DESTINATION_PORT + CONST_INVALID_DESTINATION_PORT_NUMBER_MAX + CONST_DESTINATION_PORT_RESERVED+ CONST_USE_DESTINATION_PORT_FROM_NVM

