parameters:
- name: build_target
  type: string
  default: tec0204
- name: cleanup
  type: boolean
  default: true
- name: update_cache
  type: boolean
  default: true
- name: vitis_version
  type: string
  default: 2021.2
- name: path_to_dtb_file
  type: string
  default: ""

steps:
  - template: /devops/templates/steps/mount-storage-account.yml
    parameters:
      sa_user_name: $(swbuildir2st-user)
      sa_user_password: $(swbuildir2st-key)
      sa_uri: //swbuildir2st.file.core.windows.net/debian-build
      mountdir: /mnt/debian-build
  
  - template: /devops/templates/steps/docker-login.yml
    parameters:
      user: $(ir2acr-pull-user)
      token: $(ir2acr-pull-password)
      host: ir2acr.azurecr.io


  
  - template: /devops/templates/steps/prepare_generic_infrastructure.yml
    parameters:
      build_target: ${{ parameters.build_target }}

  - bash: |
      set -e

      echo "Target:"
      echo " - TARGET: ${{ parameters.build_target }}"
      echo "##vso[task.setvariable variable=TARGET]${{ parameters.build_target }}"

      echo "Deploy artifact:"
      echo " - UPDATE_CACHE: ${{ parameters.update_cache }}"
      echo "##vso[task.setvariable variable=UPDATE_CACHE]${{ parameters.update_cache }}"

      echo "Vitis version:"
      echo " - VITIS_VERSION: ${{ parameters.vitis_version }}"
      echo "##vso[task.setvariable variable=VITIS_VERSION]${{ parameters.vitis_version }}"

      echo "Path to DTB file:"
      echo " - PATH_TO_DTB_FILE: ${{ parameters.path_to_dtb_file }}"
      echo "##vso[task.setvariable variable=PATH_TO_DTB_FILE]${{ parameters.path_to_dtb_file }}"

      echo "###############################################################"
      echo "Load target settings: "
      echo "..............................................................."
      echo source $(Build.SourcesDirectory)/devops/scripts/targets/${{ parameters.build_target }}.sh ${DOCKCON_ARTIFACTS_DIR}
      source $(Build.SourcesDirectory)/devops/scripts/targets/${{ parameters.build_target }}.sh ${DOCKCON_ARTIFACTS_DIR}

      echo "###############################################################"
      echo "Getting the artifacts: "
      echo "..............................................................."
      sudo rsync -ah --progress ${MOUNT_DIR}/${TARGET_SETTINGS["PATH_KERNEL_ST"]} ${ARTIFACTS_DIR}/

      echo "###############################################################"
      echo "Additional ENV path configured: "
      echo "..............................................................."

      echo "Artifacts: "
      echo " - PATH_KERNEL: ${TARGET_SETTINGS["PATH_KERNEL"]}"

      echo "##vso[task.setvariable variable=PATH_KERNEL]${TARGET_SETTINGS["PATH_KERNEL"]}"

    displayName: 1.1 - Prepare infrastructure
    condition: or(
                eq('${{ parameters.build_target }}', 'zcu102'),
                eq('${{ parameters.build_target }}', 'tec0204')
                )

  - bash: |
      set -e

      docker run -td --rm -v $(Build.SourcesDirectory):/ws --name a-core-debian-base-image-container ir2acr.azurecr.io/a-core-debian-base-image:latest /bin/bash
    displayName: 2.1 - Launching docker container

  - bash: |
      set -e

      echo "Download pre-built DTB..."

      if [ -d "$PATH_TO_DTB_FILE" ]; then
        echo "Using DTB from Storage account..."
        sudo rsync -ah --progress ${MOUNT_DIR}/cache/${VITIS_VERSION}/${TARGET}/dtb/system.dtb ${OUT_DIR}
      else
        echo "Using DTB from the current pipeline run..."
        sudo rsync -ah --progress ${PATH_TO_DTB_FILE} ${OUT_DIR}
      fi

      echo "Finished download pre-built DTB."
    displayName: 2.2 - Download pre-built DTB

  - bash: |
      set -e

      echo "Checking if dtb is available..."

      if [ -f "${OUT_DIR}/system.dtb" ]; then
        echo "${OUT_DIR}/system.dtb was found."
        echo "##vso[task.setvariable variable=create_dtb_result]Succeeded"
      else
        echo "${OUT_DIR}/system.dtb not found."
        echo "##vso[task.setvariable variable=create_dtb_result]Failed"
      fi
    displayName: 2.3 - Checking if dtb is available...


  - bash: |
      echo "Starting build of kernel..."

      docker exec -t -e TARGET="${TARGET}" -e PATH_KERNEL="${PATH_KERNEL}" -e DOCKCON_OUT_DIR="${DOCKCON_OUT_DIR}" a-core-debian-base-image-container bash -c "\
        source /opt/Xilinx/Vitis/2021.2/settings64.sh; \
        echo /ws/software/os/debian/kernel/build_kernel.sh -t ${TARGET} -d ${DOCKCON_OUT_DIR}/system.dtb -o ${DOCKCON_OUT_DIR}; \
        /ws/software/os/debian/kernel/build_kernel.sh -t ${TARGET} -d ${DOCKCON_OUT_DIR}/system.dtb -o ${DOCKCON_OUT_DIR}" || exit 1

      echo "Finished build of kernel."
    displayName: 3.1 - Build kernel
    condition: |
                and(
                    ne(variables['PATH_KERNEL'], ''),
                    eq(variables['create_dtb_result'], 'Succeeded')
                  )

  - bash: |
      set -e

      echo "Checking if kernel is available..."

      cd $(OUT_DIR)
      kernel_filename=$(find * -type f -name 'linux-itb-*');
      echo "Found file was: $kernel_filename"

      if [[ "$kernel_filename" == *"linux-itb-"* ]];then
        echo "##vso[task.setvariable variable=kernel_pckg_filename;isOutput=true]$kernel_filename"
        echo "##vso[task.setvariable variable=kernel_pckg_artifactname;isOutput=true]$(Agent.JobName)-$(TARGET)-sw-debian-build-kernel-$(System.StageAttempt)-$(System.JobAttempt)"
        echo "##vso[task.setvariable variable=build_kernel_result]Succeeded"

        if [[ "${UPDATE_CACHE}" == "True" ]]; then
          sudo mkdir -p ${MOUNT_DIR}/cache/${VITIS_VERSION}/${TARGET}/kernel/
          sudo rsync -ah --progress ${OUT_DIR}/$kernel_filename ${MOUNT_DIR}/cache/${VITIS_VERSION}/${TARGET}/kernel/
        fi
      else
        echo "${OUT_DIR}/$kernel_filename not found."
        echo "##vso[task.setvariable variable=build_kernel_result]Failed"
      fi
    name: KernelStep
    displayName: 3.2 - Checking if kernel is available...

  - publish: $(Build.SourcesDirectory)/build/out/$(KernelStep.kernel_pckg_filename)
    artifact: $(KernelStep.kernel_pckg_artifactname)
    displayName: 3.3 - Publish kernel package
    condition: eq(variables['build_kernel_result'], 'Succeeded')

  - bash: |
      set -e

      echo "removing a-core-debian-base-image-container...." 
      docker rm -f a-core-debian-base-image-container
      echo "Container removed........."
      echo "Clean Enabled: ${{ parameters.cleanup }}"
      if [[ "${{ parameters.cleanup }}" == "True" ]]; then  
        echo "Cleaning-up..."
        sudo rm -rf $(Build.SourcesDirectory)/software/os/debian
        sudo rm -rf $(OUT_DIR)
      else
        echo "Cleanup is disabled. Skipping..."
      fi
    displayName: 4 - Cleaning-up
