parameters:
- name: build_target
  type: string

steps:
  - bash: |
      set -e

      echo "###############################################################"
      echo "Printing pipeline configuration: "
      echo "..............................................................."

      echo "Specified values: "
      echo " - Build target: ${{ parameters.build_target }}"

      echo "###############################################################"
      echo "Creating folders: "
      echo "..............................................................."

      ARTIFACTS_DIR="$(Build.SourcesDirectory)/build/download"
      DOCKCON_ARTIFACTS_DIR="/ws/build/download"
      OUT_DIR="$(Build.SourcesDirectory)/build/out"
      DOCKCON_OUT_DIR="/ws/build/out"
      TMP_DIR="$(Build.SourcesDirectory)/software/os/debian/build/tmp"
      DOCKCON_TMP_DIR="/ws/software/os/debian/build/tmp"
      MOUNT_DIR="/mnt/debian-build"

      echo "Creating folders... "
      echo "Creating $ARTIFACTS_DIR... "
      mkdir -p $ARTIFACTS_DIR
      echo "Creating $OUT_DIR... "
      mkdir -p $OUT_DIR
      echo "Creating $TMP_DIR... "
      mkdir -p $TMP_DIR

      echo "##vso[task.setvariable variable=ARTIFACTS_DIR]$ARTIFACTS_DIR"
      echo "##vso[task.setvariable variable=DOCKCON_ARTIFACTS_DIR]$DOCKCON_ARTIFACTS_DIR"
      echo "##vso[task.setvariable variable=OUT_DIR]$OUT_DIR"
      echo "##vso[task.setvariable variable=DOCKCON_OUT_DIR]$DOCKCON_OUT_DIR"
      echo "##vso[task.setvariable variable=TMP_DIR]$TMP_DIR"
      echo "##vso[task.setvariable variable=DOCKCON_TMP_DIR]$DOCKCON_TMP_DIR"
      echo "##vso[task.setvariable variable=MOUNT_DIR]$MOUNT_DIR"

    displayName: Prepare generic infrastructure