^INCLUDE:jenkins/configs/includes/properties.yaml<abortIfNotLatest=abortIfNotLatest: "soft">; # aborts the PR's current build if there is a newer one running

uc1: FR5CU_DNNN1_NNN_N_XX_2_uC1
uc2: FR5CU_DENN1_CEN_N_XX_2_uC2

cmake_cfg_path: ad_radar_apl/tools/cmake/cfg

hw: C0
hw_C1: C1
testHwU: fr5cu
cantataBuildType : partial
testStU: 6501
testStU_C1: 001f2
user_id: cis9lr

filter: "check_dsp_error_table;check_dsp_opmode;check_dsp_spu_status;check_daddy_error_information;check_dem_events;check_locations;check_trap_information;check_safe_state;check_Location_Interface;check_smu;swTest_checkSendInSpec;swTest_checkSendTemporaryState;swTest_checkPersistentstate"
test_mode: ""

<%
int order = 0
%>

pipelines:
- nodes: 
  - label: ATR
    nodeOfflineAfterBuild: ^Exec.*
    executionOrder: 0
    skipIfOnlyFilesChanged:
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedList.yaml;
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListDoxygen.yaml;
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListAutomatedTest.yaml;
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/FetchTags.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader.yaml<execOrder=${++order}, user_id=^YAML:user_id;>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader_archive.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GeneratePDM.yaml<execOrder=${++order}, build_variant=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/CheckFluxErrors.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/CheckFluxDetails.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/BuildBCT.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;, cfg_path_uc1=ad_radar_apl/tools/builder/cubas_gen_^YAML:uc1;.cfg, cfg_path_uc2=ad_radar_apl/tools/builder/cubas_gen_^YAML:uc2;.cfg>;
    - ^INCLUDE:jenkins/configs/includes/ChangedFiles.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/CantataHost.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;, buildType=^YAML:cantataBuildType;>;
    
  - label: ATR
    nodeOfflineAfterBuild: ^Exec.*
    executionOrder: 0
    skipIfOnlyFilesChanged:
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedList.yaml;
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListCantata.yaml;
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/FetchTags.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader.yaml<execOrder=${++order}, user_id=^YAML:user_id;>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader_archive.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GeneratePDM.yaml<execOrder=${++order}, build_variant=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/Doxygen.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/FR5CUSpecGen.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/BuildSW.yaml<execOrder=${++order}, build_variant=^YAML:uc1;, cfg_path=^YAML:cmake_cfg_path;, variant=uc1, threshold=175>;
    - ^INCLUDE:jenkins/configs/includes/BuildSW.yaml<execOrder=${++order}, build_variant=^YAML:uc2;, cfg_path=^YAML:cmake_cfg_path;, variant=uc2, threshold=193>;
    - ^INCLUDE:jenkins/configs/includes/PlantContainer_PR.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/resViz.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
#   - ^INCLUDE:jenkins/configs/includes/QACDeltaCheck.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
   
#  - label: L4_Prem_C0
#    executionOrder: 1
#    skipIfOnlyFilesChanged:
#    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedList.yaml;
#    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListDoxygen.yaml;
#    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListCantata.yaml;
#    stages:
#    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
#    - ^INCLUDE:jenkins/configs/includes/Unstash.yaml<execOrder=${++order}>;
#    - ^INCLUDE:jenkins/configs/includes/MergedHex.yaml<execOrder=${++order}, hw=^YAML:hw;, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
#    - ^INCLUDE:jenkins/configs/includes/SoftIntTestUnittest.yaml<execOrder=${++order}, hw=^YAML:testHwU;>;
#    - ^INCLUDE:jenkins/configs/includes/SoftIntTest.yaml<execOrder=${++order}, hw=^YAML:testHwU;, st = ^YAML:testStU;, filter=^YAML:filter;,tm=^YAML:test_mode;, ar=C0>;

  - label: L4_Prem_C1
    executionOrder: 1
    skipIfOnlyFilesChanged:
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedList.yaml;
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListDoxygen.yaml;
    - ^INCLUDE:jenkins/configs/includes/skipFilesChangedListCantata.yaml;
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/Unstash.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/MergedHex.yaml<execOrder=${++order}, hw=^YAML:hw;, uc1=^YAML:uc1;, uc2=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/SoftIntTestUnittest.yaml<execOrder=${++order}, hw=^YAML:testHwU;>;
    - ^INCLUDE:jenkins/configs/includes/SoftIntTest.yaml<execOrder=${++order}, hw=^YAML:testHwU;, st = ^YAML:testStU_C1;, filter=^YAML:filter;,tm=^YAML:test_mode;, ar=C1>;
    
  - label: ATR
    executionOrder: 0
    stages:
    - ^INCLUDE:jenkins/configs/includes/CheckoutSCM.yaml<execOrder=${order=0}>;
    - ^INCLUDE:jenkins/configs/includes/FetchTags.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/GenerateHeader.yaml<execOrder=${++order}, user_id=^YAML:user_id;>;
    - ^INCLUDE:jenkins/configs/includes/GeneratePDM.yaml<execOrder=${++order}, build_variant=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/scom.yaml<execOrder=${++order}, uc2=^YAML:uc2;>;
    - ^INCLUDE:jenkins/configs/includes/ChangedFiles.yaml<execOrder=${++order}>;
    - ^INCLUDE:jenkins/configs/includes/QACDeltaCheck.yaml<execOrder=${++order}, uc1=^YAML:uc1;, uc2=^YAML:uc2;>; 

