trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - develop
  drafts: false


pool:
  name: cx-lnx-l-vmss

stages:
  - template: /devops/templates/stages/build-a-core-base-image-template.yaml
    parameters:
      build_reason: pr