trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - develop
  drafts: false

resources:
  containers:
  - container: a-core-application-container
    image: artifactory.boschdevcloud.com/zugspitze-series-docker-local/a-core-application:latest
    endpoint: sc-ado-docker-registry-artifactory
    options: --user 0:0 --privileged
    volumes: # Volumes to mount on the container.
    - /var/tmp/conan_cache:/var/tmp/conan_cache
    env: # Variables to map into the container's environment.
      TARGET: armv8
      TYPE: debug
      MIDDLEWARE_INSTANCE: tec0204_linux
      AOS_VERSION: default
      ENABLE_CLANG_TIDY_CHECKS: 'ON'

stages:
  - template: /devops/templates/stages/build-a-core-application-template.yaml
    parameters:
      build_reason: pr
      vmss: cx-lnx-l-vmss
      trigger_ct: false
